name: HG-Plugin
author: bySenom
description: 'HG-Plugin'
source: 'https://github.com/Bysenom/HG-Plugin'
version: '${project.version}'
api-version: '1.20'
load: STARTUP

commands:
  hg:
    description: 'HG Command'
    usage: /hg

main: de.bysenom.hg_plugin.Main
playerscoreboard-class: de.bysenom.hg_plugin.PlayerScoreboard
cooldownmanager-class: de.bysenom.hg_plugin.CooldownManager
