name: HG-Plugin
author: bySenom
description: 'HG-Plugin'
source: 'https://github.com/Bysenom/HG-Plugin'
version: '${project.version}'
api-version: '1.20'
load: STARTUP
commands:
  fly:
    description: Toggles flight mode
    usage: /fly
  hgjoin:
    description: Joins the HG
    usage: /hgjoin
  hgstart:
    description: Force Start the Game
    usage: /hgstart

main: de.bysenom.hg_plugin.Main
fly-class: de.bysenom.hg_plugin.commands.Fly
hgjoin-class: de.bysenom.hg_plugin.commands.HGJoin
lobbycountdown-class: de.bysenom.hg_plugin.handlers.LobbyCountdown
playerjoinlistener-class: de.bysenom.hg_plugin.handlers.PlayerJoinListener
invincibilityhandler-class: de.bysenom.hg_plugin.handlers.InvincibilityHandler
buildhandler-class: de.bysenom.hg_plugin.handlers.BuildHandler
teleporthandler-class: de.bysenom.hg_plugin.handlers.TeleportHandler
itemhandler-class: de.bysenom.hg_plugin.handlers.ItemHandler
invclearhandler-class: de.bysenom.hg_plugin.handlers.InvClearHandler
souphealing-class: de.bysenom.hg_plugin.mechanics.SoupHealing
anchor-class: de.bysenom.hg_plugin.kits.anchor

# This sets PlaceholderAPI as an optional dependency for your plugin.
depend: [PlaceholderAPI]

