name: HG-Plugin
author: bySenom
description: 'HG-Plugin'
source: 'https://github.com/Bysenom/HG-Plugin'
version: '1.0-SNAPSHOT'
api-version: '1.20'
load: STARTUP

commands:
  hg:
    description: "Join the Hunger Games"
    aliases: ["hungergames"]
    delay: 20              # Optional delay of 1 second (20 ticks)

main: de.bysenom.hg_plugin.Main
playerscoreboard-class: de.bysenom.hg_plugin.PlayerScoreboard
lobbysystem-class: de.bysenom.hg_plugin.LobbySystem
cooldownmanager-class: de.bysenom.hg_plugin.CooldownManager
