name: HG-Plugin
author: bySenom
description: 'HG-Plugin'
source: 'https://github.com/Bysenom/HG-Plugin'
version: '1.0-SNAPSHOT'
api-version: '1.20'
load: STARTUP

main: de.bysenom.hg_plugin.main
scoreboard-class: de.bysenom.hg_plugin.PlayerScoreboard

